export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_SCHEDULE_REQUESTED = 'GET_SCHEDULE_REQUESTED';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAILED = 'GET_SCHEDULE_FAILED';

export const ADD_REQ_SHIFT_REQUESTED = 'ADD_REQ_SHIFT_REQUESTED';
export const ADD_REQ_SHIFT_SUCCESS = 'ADD_REQ_SHIFT_SUCCESS';
export const ADD_REQ_SHIFT_FAILED = 'ADD_REQ_SHIFT_FAILED';

export const SET_LOGGED_USER = 'SET_LOGGED_USER'