export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const ADD_USER_REQUESTED = 'ADD_USER_REQUESTED';
export const ADD_USER_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USERS_FAILED';

export const GET_MSGS_REQUESTED = 'GET_MSGS_REQUESTED';
export const GET_MSGS_SUCCESS = 'GET_MSGS_SUCCESS';
export const GET_MSGS_FAILED = 'GET_MSGS_FAILED';

export const ADD_MSG_REQUESTED = 'ADD_MSG_REQUESTED';
export const ADD_MSG_SUCCESS = 'ADD_MSG_SUCCESS';
export const ADD_MSG_FAILED = 'ADD_MSG_FAILED';